"""add human in the loop qa reviews

Revision ID: 7b2c8550b81a
Revises: a04814dbcda8
Create Date: 2026-09-01 03:02:41.669733
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '7b2c8550b81a'
down_revision: Union[str, Sequence[str], None] = 'a04814dbcda8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qa_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('suggestion_id', sa.Integer(), nullable=False),
    sa.Column('recommendation', sa.String(length=32), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('signals_json', sa.Text(), nullable=False),
    sa.Column('requires_human', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['suggestion_id'], ['suggestions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'suggestion_id', name='uq_qa_review_tenant_suggestion')
    )
    op.create_index(op.f('ix_qa_reviews_recommendation'), 'qa_reviews', ['recommendation'], unique=False)
    op.create_index(op.f('ix_qa_reviews_suggestion_id'), 'qa_reviews', ['suggestion_id'], unique=False)
    op.create_index(op.f('ix_qa_reviews_tenant_id'), 'qa_reviews', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qa_reviews_tenant_id'), table_name='qa_reviews')
    op.drop_index(op.f('ix_qa_reviews_suggestion_id'), table_name='qa_reviews')
    op.drop_index(op.f('ix_qa_reviews_recommendation'), table_name='qa_reviews')
    op.drop_table('qa_reviews')
    # ### end Alembic commands ###
